# Generated by Django 3.2.13 on 2022-10-17 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('payment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('content_quote', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('content_approved', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BigQuery',
        ),
        migrations.AddField(
            model_name='content',
            name='youtube',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube', to='bean.youtube'),
        ),
    ]
